language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.6.*

before_script:
  - composer self-update
  - composer install
  - mysql -e 'create database sleepness;'

script:
  - phpunit
